{% set name = "lammpsio" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lammpsio-{{ version }}.tar.gz
  sha256: 68a8f335b80526b1fa614ed1479c151fb7ab349660d8a418dc949e08fa5e0af3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - packaging

test:
  imports:
    - lammpsio
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mphowardlab/lammpsio
  summary: Python tools for working with LAMMPS
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mphoward
