{% set name = "lammpsio" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lammpsio-{{ version }}.tar.gz
  sha256: bea09ec5aabadecacc772fb009975df08f5626b10dbb5941ca372d018950253a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=46.4.0
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - packaging

test:
  imports:
    - lammpsio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mphowardlab/lammpsio
  summary: Python tools for working with LAMMPS
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mphoward
