schema_version: 1

context:
  version: 0.10.0
  python_min: 3.12

package:
  name: lammpsio
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/lammpsio/lammpsio-${{ version }}.tar.gz
  sha256: 9cb843de553b2c29612ca9b4cd23687c1e45287b8a795176b931cb8496315889

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.1
    - packaging

tests:
  - python:
      imports:
        - lammpsio
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  homepage: https://lammpsio.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python tools for working with LAMMPS
  repository: https://github.com/mphowardlab/lammpsio
  documentation: https://lammpsio.readthedocs.io

extra:
  recipe-maintainers:
    - mphoward
